apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-nginx
  name: web-svc2
 # namespace: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-nginx
  type: NodePort