apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: smokeping
  name: smokeping
  namespace: apu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smokeping
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smokeping
    spec:
      containers:
      - image: linuxserver/smokeping
        name: smokeping
        
